# Place checks
on place barrier:
    if player doesn't have permission "zuko.illegals":
        execute console command "ban %player% Zuko.Illegals: Tried to place banned block (BARRIER)"
        cancel event




on place bedrock:
    if player doesn't have permission "zuko.illegals":

        execute console command "ban %player% zuko.illegals: Tried to place banned block (BEDROCK)"
        cancel event





#Drop checks
on drop bedrock:
    if player doesn't have permission "zuko.illegals":
        execute console command "ban %player% zuko.illegals: Tried to drop banned block (BEDROCK)"
        cancel event




on drop barrier:
    if player doesn't have permission "zuko.illegals":
        execute console command "ban %player% zuko.illegals: Tried to drop banned block (BARRIER)"
        cancel event




# Inventory checks
every 0.5 seconds:
    loop all players: #Check if a player has bedrock
        if loop-player has bedrock:
            if loop-player doesn't have permission "zuko.illegals": 
                loop all players: #Check if a player can receive the report 
                    if loop-player-2 has permission "zuko.illegals-reports":
                        send "" to loop-player-2 
                        send "&8======================" to loop-player-2
                        send "&cAnti-Illegals &7>> %loop-player-1% Ma Nielegalny item (Bedrock)" to loop-player-2
                        send "&8======================" to loop-player-2
                        send "" to loop-player-2

every 0.5 seconds:
    loop all players:
        if loop-player-1 has Barrier Block: #Check for item
            if loop-player doesn't have permission "zuko.illegals": #Check for permission to have the item
                loop all players: #Check for players with permission "zuko.illegals-reports
                    if loop-player-2 has permission "zuko.illegals-reports": #Checks for permission roceiver reports
                        send "" to loop-player-2 
                        send "&8======================" to loop-player-2
                        send "&cAnti-Illegals &7>> %loop-player-1% Ma Nielegalny item (Barrier Block)" to loop-player-2
                        send "&8======================" to loop-player-2
